steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/priyanka-pipeline', '/.']
    # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/priyanka-pipeline']
      # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cloud-run-deploy', '--image', 'gcr.io/$PROJECT_ID/priyanka-pipeline', '--region', 'europe-west2', '--platform', 'managed', '--allow-unauthenticated']
images:
  - gcr.io/$PROJECT_ID/priyanka-pipeline
