apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: php-apache
        author: priyanka
  template:
    metadata:
      labels:
        app: php-apache
        author: priyanka
    spec:
      containers:
      - name: php-apache
        image: gcr.io/searce-playground-v1/priyanka-pipeline
        env:
          - name: PORT
            value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 10Mi
        ports:
        - containerPort: 80