apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app: php-apache
    author: priyanka
spec:
  type: {{ .Values.Service.type }}
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: php-apache
    author: priyanka